name: Run pre-commit on push

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fortellar/docker-terraform:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - name: Run Trivy on Terraform files
        if: ${{ github.event.head_commit.modified && contains(join(github.event.head_commit.modified, ','), '.tf') }}
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "."
          format: "table"
          exit-code: "1"
